name: Publish Docker Image

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4.1.0
        with:
          images: ghcr.io/invotyx/xclusiveme-frontend # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get BASE_URL (prod)
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: echo "BASE_URL=$(echo https://api.xclusiveme-dev.tk/api)" >> $GITHUB_ENV
      - name: Get BASE_URL (dev)
        if: github.ref == 'refs/heads/dev'
        shell: bash
        run: echo "BASE_URL=$(echo https://api.dev.xclusiveme.ga/api)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            REACT_APP_BASE_URL=${{ env.BASE_URL }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
